### ISSUE TITLE
Errors in import for app/core/level

### ISSUE THREAD

**Issue by Supamiu** [code-chunks/angular2-logger#26] opened 2016-04-22 07:36 UTC
imports/exports have been renamed using a tool or something like that (PHPStorm does this sometimes) causing all /**/level imports to become /**/level.ts imports, which creates an error when using System.js to import.

core.ts:
`export * from "./app/core/level.ts";`

core.d.ts:
`export * from "./app/core/level.ts";`

logger.d.ts:
`import { Level } from "./level.ts";`

**Comment by langley-agm** [comment] 2016-04-22 15:21
@Supamiu Thanks for taking the time to raise the issue. 

I understand what you are referring to and I will probably change it soon. However I cannot reproduce an error with the way it is now by following the Getting Started instructions can you give me more information on how this error is happening to you?

The bundle file already uses system to load the plugin classes, you don't have to set it up again, just add the bundled js file in a script tag, are you creating a different configuration yourself ? Can you show it to me?

I want to reproduce it before applying the fix so I make sure I can test that scenario in future releases.

**Comment by Supamiu** [comment] 2016-04-26 08:22
I had this issue using jasmine to do unit tests against a service that uses your package.

Here is the System.config that created the error:

    System.config({
            map: {
                'angular2': 'node_modules/angular2',
                'rxjs': 'node_modules/rxjs'
            },
            defaultJSExtensions: true,
        });

Problem is that defaultJSExtensions automatically adds ".js" to every imports, so it is looking for level.ts.js instead of level.js.

To fix this issue, I disabled auto JS extensions on angular2-logger, but if you simply change imports from "level.ts" to imports from "level".

Here is the workaround:

    System.config({
            map: {
                'angular2': 'node_modules/angular2',
                'rxjs': 'node_modules/rxjs'
            },
            defaultJSExtensions: true,
            packages: {
                'angular2-logger': {
                    defaultExtension: false
                }
            }
        });

**Comment by langley-agm** [comment] 2016-05-02 00:19
@Supamiu 

`core.d.ts` and `logger.d.ts` are generated files and `core.ts` is doing an export, not an import, I believe the file that was causing you this issue is: `app/core/logger.ts`, I hadn't noticed that one.

I fixed them all in 0.2.3, let me know if your issue is fixed now without the need of the workaround so I can close this ticket please. And thanks for your contribution! =)

**Closed** 2016-05-02 07:53 UTC
Labels: bug, fixed
